FROM alpine as builder
ARG SIGNED_URL FILE_NAME
RUN apk add --no-cache zstd
RUN wget --no-verbose -O ${FILE_NAME} ${SIGNED_URL} && \
    zstd -o ./dufs -d ${FILE_NAME} && \
    mv dufs /bin/

FROM scratch
COPY --from=builder /bin/dufs /bin/dufs
STOPSIGNAL SIGINT
ENTRYPOINT ["/bin/dufs"]
