FROM --platform=linux/amd64 docker.io/messense/rust-musl-cross:x86_64-musl AS builder
COPY . .
RUN cargo install --profile release-with-debug --path . --root /

FROM alpine
RUN apk add --no-cache xz-libs libgcc libstdc++ libc6-compat
COPY --from=builder /usr/lib/lib* /usr/lib/
COPY --from=builder /bin/dufs /bin/dufs
STOPSIGNAL SIGINT
