build:
	npm run build-css
	API_LOGIN_URL=http://localhost:3000/auth/login ~/.cargo/bin/trunk build

css:
	npm run dev

serve:
	API_LOGIN_URL=http://localhost:3000/auth/login ~/.cargo/bin/trunk serve --port 3030
